
-- BOARDS (게시글) 테이블 생성
CREATE TABLE BOARDS(
	 IDX		INT				PRIMARY KEY
	,TITLE		VARCHAR2(100)	NOT NULL
	,CONTENT	VARCHAR2(4000)	NOT NULL
	,USERID		VARCHAR2(20)	NOT NULL
	,REGNUM		INT				NOT NULL
	,REGDATE	DATE			NOT NULL
	
);
