create or replace NONEDITIONABLE PACKAGE BODY PKG_BOARDS AS

  PROCEDURE PROC_SEL_BOARDS(
	 IN_IDX		IN		VARCHAR2
	,O_CUR		OUT		SYS_REFCURSOR
 ) AS
  BEGIN
    
	OPEN O_CUR FOR
	SELECT IDX, TITLE, USERID, REGNUM, CONTENT,
	DECODE(TO_CHAR(REGDATE,'YY/MM/DD'), TO_CHAR(SYSDATE,'YY/MM/DD')
			, TO_CHAR(REGDATE,'HH24:MI:SS')
			, TO_CHAR(REGDATE,'YYYY-MM-DD')) AS REGDATE
	FROM BOARDS
	WHERE TO_CHAR(IDX) LIKE '%' || IN_IDX
	ORDER BY IDX DESC
	;
	
  END PROC_SEL_BOARDS;
  
	PROCEDURE PROC_INS_BOARDS(
		 IN_TITLE	IN		VARCHAR2
		,IN_CONTENT	IN		VARCHAR2
		,IN_USERID	IN		VARCHAR2
	)AS
	BEGIN
	
		INSERT INTO BOARDS VALUES( (SELECT NVL(MAX(IDX),0)+1 FROM BOARDS), IN_TITLE, IN_CONTENT, IN_USERID, 1, SYSDATE);
		
	END PROC_INS_BOARDS;

	PROCEDURE PROC_DEL_BOARDS(
		IN_IDX		IN		VARCHAR2
	)AS
	
	BEGIN
		DELETE FROM BOARDS WHERE IDX = IN_IDX;
		UPDATE BOARDS
		SET IDX = IDX-1
		WHERE IDX > IN_IDX
		;
	END PROC_DEL_BOARDS;
	
	PROCEDURE PROC_UP_BOARDS(
		 IN_TITLE	IN		VARCHAR2
		,IN_CONTENT	IN		VARCHAR2
		,IN_IDX		IN		VARCHAR2
	)AS
	BEGIN
	
		UPDATE BOARDS SET TITLE = IN_TITLE, CONTENT = IN_CONTENT, REGDATE = SYSDATE WHERE IDX = IN_IDX;
		
	END PROC_UP_BOARDS;

END PKG_BOARDS;
